# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fdf26d803641a418503e4ce7877966cbd136e356fc5a8894b847214167ad7a2e82ea7b3a084cb6c69722380efb005fe60d85d23d972c955c64af8cce4a6a7b3

test:
  secret_key_base: 2a22a497065edf4d76923f07d58e472e12e28b01654b9807a1d916c4f5495055782ad72473bef6cc4b0861d7fb96e0d8a27654b0a03b1fc7863e04b6100f4fda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
