# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce8b5ebdf9752f587c8302336a332666358af551d9789cf89ce7ad6321062f9e2ed3421dcf0900e9455ec24a767b2dd6c21e19cad54970263fb7d783f8cf5f7b

test:
  secret_key_base: 553e835845aaf738aba67a854cd2a0b9ea3bb4c4d0e79e536f6aa56869c9f97dc023d5c9e3b6d2dcad894ec4998dd3c151ff6181a41f9f83bd3b75ed9d45ab95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
