# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dfb9c01ee66e6eeffda5e9c580bd34736f768443ac2701767e94aa442092d7dc24733097ea4619ece961b1c3792774acd3f8bdcb4bb58456f1273a3fdf5dc63

test:
  secret_key_base: e62eaad0dce5d16852c5f66b1fd7bbfb3e8ca4bb6031c5648b1c2967bcb9b901f129abeec7906320580de31c3dc6d741a222130524185f1aff309574fcbaa254

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
